### ISSUE TITLE
Combining more than two playlists results in empty playlist

### ISSUE THREAD

**Issue by Vadeinspace** [jeroentvb/spicetify-combined-playlists#11] opened 2023-03-04 01:18 UTC
Combining more than two playlists results in empty playlist- When combining two seems to work fine, though.

<img width="472" alt="print1" src="https://user-images.githubusercontent.com/96423568/222867286-6617165e-621c-40f8-ad80-2b986197deec.png">

<img width="522" alt="oriny2" src="https://user-images.githubusercontent.com/96423568/222867279-07e766f7-2ac5-481f-abe0-05ac6b621a95.png">

**Comment by jeroentvb** [comment] 2023-04-18 17:49
I've just tried combining 3 playlist into a new one (one generated by the app, one pre made), and I can't seem to be able to reproduce your issue.

Could you provide reproduction steps, or try opening the dev console and check if any errors are being thrown by combined-playlists, or send a screenshot/log of the console.

**Comment by jeroentvb** [comment] 2023-09-03 10:50
Closing as cannot reproduce.

**Closed by jeroentvb** 2023-09-03 10:50 UTC
Labels: bug
